### PR TITLE
296 mlord notifications in calendar

### LINKED ISSUE #279: Notification Create/Modify/Delete based on task made and reminder set in form
Implement the notification Create/Modify/Delete based on task made and reminder set in form in the CareConnect Calendar Assistant.

### LINKED ISSUE #280: Calendar customizations based on dates and other aspects
Implement the ability for the calendar to allow customizations based on dates and other aspects in the CareConnect Calendar Assistant

### LINKED ISSUE #296: Calendar uses Notification system for reminders
Ensure the calendar uses notification system for reminders.

### LINKED ISSUE #297: Calendar can add/delete/modify notifications
Ensure the calendar can add/delete/modify notifications in the CareConnect system.

### LINKED ISSUE #405: Correct Feedback that was given in PR for Demo 1
Below is a list of items that need correcting for the Calendar Assistant that were merged for Demo 1 but need to be fixed:

-  TaskControllerV2:  add javadocs or comment on what id is
-  TaskServiceV2: Could you create a "TaskNotFoundException" or "NotFoundException" instead of using the generic AppException
-  calendar_assisiant: split this up into widgets

### LINKED ISSUE #415: Patients can't see tasks
Patients are not able to see tasks in the calendar.

### PR DESCRIPTION
**Pull request by lordmitchell**
The branch for Pull request was created to fully flesh out the second iteration of the Calendar Assistant not limited by the Demo 1 deadline. This was needed to change functionality to the backend and allow for expansion of reoccurring task including allowing each reoccurring task to be considered its own task for CRUD actions. This branch did address some GitHub issues and those issues are:
#279 
#280 
#296 
#297 
#405 
#415

### CODE REVIEW

File: careconnect2025/backend/core/src/main/java/com/careconnect/model/Task.java [hunk 1]
```diff
@@ -23,35 +48,164 @@
...
+     * Example: A "Daily Medication" parent task may generate child tasks
+     * for individual days. The children reference the parent task’s ID here.
+     * </p>
+     * <p>
+     * Optional.
+     * </p>
+     */
     @Nullable
-    private String daysOfWeek; // 7 long list for each day of the week
+    private Long parentTaskId;
```
Comment (vohrr) [inline careconnect2025/backend/core/src/main/java/com/careconnect/model/Task.java:209]: Are scheduled notifications going to typically reference parent tasks or children tasks?

File: careconnect2025/backend/core/src/main/java/com/careconnect/util/TaskMapper.java
Comment (vohrr) [inline careconnect2025/backend/core/src/main/java/com/careconnect/util/TaskMapper.java:1]: I think it makes more sense for this to go in  /util folder.

File: careconnect2025/backend/core/src/main/java/com/careconnect/service/v2/TaskServiceV2.java [hunk 2]
```diff
@@ -1,127 +1,959 @@
...
+            }
+
+            for (ScheduledNotificationDTO n : dto.getNotifications()) {
+                ScheduledNotification sn = ScheduledNotification.builder()
+                        .receiverId(n.getReceiverId())
+                        .title(n.getTitle())
+                        .body(n.getBody())
+                        .notificationType(n.getNotificationType())
+                        .scheduledTime(LocalDateTime.parse(n.getScheduledTime(), FORMATTER))
+                        .status("PENDING")
```
Comment (vohrr) [inline careconnect2025/backend/core/src/main/java/com/careconnect/service/v2/TaskServiceV2.java:627]: This is going to delete the record of all historic notifications that have already been sent. Is that intended?

File: careconnect2025/frontend/lib/features/tasks/models/task_model.dart [hunk 3]
```diff
@@ -59,139 +76,94 @@ class Task {
                   : json['timeOfDay']['minute'],
             )
           : null,
-      userId: json['patient']?['id'],
+      userId: json['patientId'],
```
Comment (vohrr) [inline careconnect2025/frontend/lib/features/tasks/models/task_model.dart]: patientId is distinctly not userId in the database. Passing a patientId in as a userId, if the model is expecting userId will cause errors. What id does this model need?

File: careconnect2025/frontend/lib/features/tasks/models/task_model.dart [hunk 4]
```diff
@@ -1,28 +1,39 @@
...
-  List<Notification_dto>? notifications;
+  List<ScheduledNotification>? notifications;
 
   //Recurrence fields
   String? frequency; // e.g., daily, weekly, monthly, yearly
   int? interval; // number of days/weeks/months between recurrences
   int? count; // number of total occurrences
   List<bool>? daysOfWeek; // e.g., [false, true, false, true, ...] for Mon/Wed
   final String? taskType; // "General" | "Lab" | "Appointment" | "custom"
+  bool applyToSeries;
```
Comment (vohrr) [inline careconnect2025/frontend/lib/features/tasks/models/task_model.dart:32]: Will the name mismatch here between the TaskDtoV2 model (updateSeries vs applyToSeries) cause errors with json serialization?

**Review by vohrr — APPROVED** [review]
Approving with a few suggestions/comments

File: careconnect2025/backend/core/src/main/java/com/careconnect/model/Task.java (hunk 1 above)
Comment (lordmitchell) [reply careconnect2025/backend/core/src/main/java/com/careconnect/model/Task.java:209]: Each task has a list of scheduled notifications. The parentTask is for anchoring when calculating reoccurrence.

File: careconnect2025/backend/core/src/main/java/com/careconnect/service/v2/TaskServiceV2.java (hunk 2 above)
Comment (lordmitchell) [reply careconnect2025/backend/core/src/main/java/com/careconnect/service/v2/TaskServiceV2.java:627]: I saw no need to archive that at this time with how the DB setup is for the app.

File: careconnect2025/frontend/lib/features/tasks/models/task_model.dart (hunk 3 above)
Comment (lordmitchell) [reply careconnect2025/frontend/lib/features/tasks/models/task_model.dart]: The user id there, is the id that the task is assigned to. As of current implementation that should only be Patient Ids. Tasks are not currently handled for being assigned to Care Givers within the CareConnect system. This definition is based from legacy defining of the object.

File: careconnect2025/frontend/lib/features/tasks/models/task_model.dart (hunk 4 above)
Comment (lordmitchell) [reply careconnect2025/frontend/lib/features/tasks/models/task_model.dart:32]: As far as my testing goes no, the frontend and backend have been able to use the JSON.

File: careconnect2025/backend/core/src/main/java/com/careconnect/util/TaskMapper.java
Comment (lordmitchell) [reply careconnect2025/backend/core/src/main/java/com/careconnect/util/TaskMapper.java:1]: Added commit to make this move, comment resolved

File: careconnect2025/frontend/lib/features/tasks/models/task_model.dart (hunk 3 above)
Comment (lordmitchell) [reply careconnect2025/frontend/lib/features/tasks/models/task_model.dart]: Last commit fixes this issue.
